### ISSUE TITLE
How to specify a specific wxWidgets version?

### ISSUE THREAD

**Issue by tester0077** [lszl84/wx_cmake_template#10]
What would be the best/preferred way to specify a specific release or minimum/maximum version for wxWidgets, rather what ever cmake can find at github ?

**Comment by lszl84** [comment]
Take a look at the list here: https://github.com/wxWidgets/wxWidgets/tags, and then use the appropriate tag name in the `GIT_TAG` parameter in `third party/wxwidgets/CMakeLists.txt`

**Comment by tester0077** [comment]
Thank you
